language: java

jdk:
  - openjdk18

# Need a full git clone in order to be able to tag the release
git:
  clone: false

install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout $TRAVIS_BRANCH
  - POM_VERSION=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec | sed -e 's/-SNAPSHOT//')
  - openssl aes-256-cbc -K $encrypted_4f0d00631887_key -iv $encrypted_4f0d00631887_iv -in .travis/gpg.asc.enc -out .travis/gpg.asc -d
  - gpg --fast-import .travis/gpg.asc

env:
  global:
    # Environment variables referenced in .travis/maven-settings.xml. To encrypt and escape values correctly, run the following
    # command and enter ENV_VAR=value when prompted:
    # read -r && travis encrypt "$(printf %q "$REPLY")"
    - secure: 0jyFMSl7c1IHxWEq/OTU5Pmax6t3UyoInmk7t2nTHathVh3KpFIdkp7ew/sJaCPBE2mnyEUPJY53sJaf8d+p0l8EJd9KXzExV9+v0WS9lH+pvTok5tBrsGJXLE8tCoK8v4liS8ErI05Qtf5baiBf03+s0j5KttMXXwb3a8g1DQXDiGaqg+l7qTgChY7Z5+Jsej+lVxEr/thEeouny+Zq3ICx63hHvAlPs86VI4YB0Aaqhj7hQHfaD6LeDHb7ka1ICSdSUm3Hd78j2TtX7t8Winkio6o5TL95gvl1h/v+5JYCAuB3CyTFuzVokPZ3JUxIPvMFXAYp8lbeq4xILb5cHNtM8lK4bkFxUNEAAWTxI+MeVT4HgMrpNdB+STsLm0dnbWqvatWiOvVL5goGiS44G71jc/nSx+jwHEaaki6m1/j2PmuXvkpv6fDna8318DhStZueTjitBs3KUqO1cqQc/f03cKhKVaPAJToLm0P7UFcmc5BsQeKUhOeCVvGf8HdQy3MOlZbKcbHjeGVXU/erUNhrL2u7e99KfqyPv/EQJwlHmtBPaqm6z29HLzUsuv07N6mC1PyqlM9bZRW3C9SVfeYTc3tgmym6vGSpggwXJBrnYKdsWh8rE1L/7iC+iBzOEL5igNZpC356uRZNYGh9MI1u1/w1vW5SWAbtTOluFQc=
    - secure: FA4ln4Aoeo1CtEyiFmbebakLIJitYn/YLbnhA+z8kgysuTHufHQoTMG3YN0S1aR8TFjAxhLai29PdqjGh7Pi+h8V8Qg8ZsRymlPCGcY1LHyyL2dldBgn+z0ikEiPZZD/02DH88hq8i6mUGK5g7tsDLbiD4jcsdkamDcSP5MJH9v4f0/Hny9RM0upuQbCnj7PuYkSdsTUeQD9ajK783JpiHbBcySGYkKkaqRbAK4PvphK8vMvrzMvUAyf8zGnkxYZrLgP1sj+eGRACkhlCQ3oxMJZ8/0nBuALhgAB4xTwbcjsNM5Sz5WBznC7rPKYWdfO829x8s3lLheLtvwT0aTBPgcCNdq3+Vv6P2t3Qr81O7RITq1SPAPfDDUZx+KPFc01LmKZ2XcXC8QbjmncwcHhcfJCqNhLoKJg8m2oPUVceD0xXFqfaOAKUAHjc59FrkgBRpN+qx2YJ39UW3Eg6siBGtK8uqREP8Q8maUkF9zS/VFVQcli50v71dgStCwHLLZUjDtQO494ttlWnUhjjblNOPDzokAANQM/rKZFZEGdJOBA7zq52k/Z83M17bYm2+WPerKktM/9B1dwyGs1idBUxl0/LlmsNImfH4PePd6zdB/WlQ0y1VXfZeCBQSymujYN/I505ySgVNcQYnsurCphA+b9MHRtEBi9RYNGzOuyXjo=
    - secure: ZNpUDkUsuGuO0p2I+6VRO4c4/amZB2knMqQmE+0ZXt93AQD7FvJOF1XiZaEYywvlBjgPTD4ZJrp//HRMaNh57B0FU2SnD8MM4JiITm3VL56nXCBCktxBMoDSmiqFdK5kIbcfIDwdNV0hHmJEVodSFVWwBeKhiJIA3S8DS41ghB5O6KOOi4iND03TfHSrjNOgNxYOUVbqKadvNsIhzxDqf00cmun4uqw6RHywmyP4BE6TcQak6cgm6TjLeqhXTmyjKSqOaIuErzV6Z5NL6mnpb2GAJe1KPBK9rItFxlxqbSUUA181PlL6Ip5s5Gd9l1WJDldy6COLnJWau2f3LSQFODXs7Xf2/RLUV8uy0ceI7HsiivnTUE1CEX1b3gVc35CAooPq0dakzQInMePrl99sR7yiMrNEWEhmYRoZcqCKWabogaMMG6wIL7AJwfyeAk63ELg7fIBMVA9NOWBV9YswqE3okACQGfX4Q/hqKYokCaDSPKAnH1Gj2jmy/S6OYg4xv9MXHZHy/dh422lU1Wcp33o3Dn1VC7Xo5pGdaDsxvOZ/zF/mPnG78YXf1zm7+AeXOs3D6fOMA5AC54k7eHqJZMmTbhDIx88wpnbWI1Wy0rm5k4g4pECsc3P93ga8ycC8IS0WIv7t9Lsk37N5TEUQQ1z8q5rDBxN+OlXQvtTXqSA=
    - secure: q7s9BPXGuQs13uI6d9jFLzW6YTKfHfyEeuhJ2wLMKWuA98apu7XeIUud8KAEcaxMp7kDMSCqMIWDTTsa7iBB9vqJuurHCGL9i0AnmiLNwPKFu1yNwXzCCEy+F0q2eM/+BNhTW6Wmo3rodn/nPZfylbSmD4mbgRf9m/l2FJaasr8QgQe5sbXwO13G359vpH+sB9E8P5OtBT6SmpBBzX7VncAaX/i0naVaAHAKktqjPByzFQH3ENTVZt/uGPkSN+XpQuOa7jEmv6GarnsyxQrft45O+OJFdA7RvFtA9+hYZi04UWYz+5R6iiYP0lkpvTd7dbqKEGi/BOIw0DWIwK8sMO9vkXu2wcJUAGoo7FGPv4MkJ/H2LCm0ln0vL5KtVrsmZg4tOymcuj+bKNGW+FIu6AE1+NataN42wltEUyaI+Sjh5E2zOrfYs7kkXJqKjpbagenvdX3r8nmmF3cjeLH3X8kQAOhrhFpZBvsx3dBBR1/ZgauR4kJAjOTgqhoDLQNz+cD+1jJmQ3//HmmiFaUDM17xjprYqNkJlBglNMK9lnovIS3Wutd9Whz6zRlV4EsgAjdure9QzrFSBUpOMZtsbX6/gv3HfHM4t35Mybg/p+oPs0Ma5oA1EA4890d+Rg570RKKV2JF4dKtqHKf9Wu4QrGR3EaFiYaXHEc89KLUpOE=
    - secure: fKAJZ9wpO1l5GXBWKg7YPwqXBng3cvhkWYFxKBj09GNr4+SKg9JmYK3Avt+4O7xaAnV/nLfTA+465NtLQ5au/8u6O77JKvQKznhUjG7C57Z2yUUY5fJa0piUNg57SfNysx1B5KpDyNp6e8i37ccxziCCy7IXNYm5lDLhQP/C9gHsJEJ95E5sGTxSE0hn1mavYKDJqT3kaVlsVwmiWOs6WylUb3nYxD3qGR4Tf3Wm77blyBxEaVTiRgTZGensfMCKVbBJnSRisFXcvL9I3Z02wmZVQJK20wYRRRLM3NMqM5cY2tN2Scoh/MIogvg/HqCQ4bDPe+PPJHplJfkYS6c8yaQsypM63ISQlrzC1lx7BeqsCyKCWWFmDANT8ccnY/C7h6AhPgJyZaQV/h8KRcHAEOX9kasfHyvtYA7RLbS/uK79Onrl7MjJ5YSx9dAiH75t1iEI8F9pnKLfLyxlmYrTtOjMv0JWuDIbRwjjiNNW7AK6xg25OSLK6ObiFJG1JcvUFFmO92OqX/OpDFNEUQ9SHd12UsG+1jTzH3zbJBVIj/1XvL41o7xO3KXbayfey8PZaSr822J89SE/m4BIgQwiVsLLKtnalYhaimR40Qk2zroFBbbAENKFetWotW/EI6PetFXJ/sCSgDz/uGr4czpnLNmsNtnNF9KtfGHSInhaTUk=

script:
  - mvn clean install -B
  - mvn org.pitest:pitest-maven:mutationCoverage -B

before_deploy:
  # Set tag to be used by releases provider
  - export TRAVIS_TAG=$POM_VERSION

deploy:
  # For any checkin to main branch, create a final version, tag it and push the artifacts to Sonatype
  - provider: script
    skip_cleanup: true
    script:
      mvn --settings .travis/maven-settings.xml release:prepare release:perform -DskipTests -Prelease -B
    on:
      branch: main

  # Releases config copied from https://docs.travis-ci.com/user/deployment/releases/ and secure key generated by following
  # https://stackoverflow.com/questions/25302518/travis-ci-setup-releases-with-github-token#answer-57032190
  - provider: releases
    api_key:
      secure: 1iMX7FINET16A2GvZLtYpZZU3pCkZg7zKkcpmiq0KGRHF2ktv5ldxb2dtCG9Lk+JAgg7O0PG/4w7NbhgR4KbQIYv1GDvybnshX7Xx1a8MLlenF7vZ/7jPq0yDQ6Sbt4RDZL4mCW5Oq2qnhrxUa3DnaAahStc2RJ7DWJUJYT0LwEl5tzPzGeBwPAKrtgN6cxMIfwGvJcWkvF6emdwMmazBfUmgXQX7Efw5lpsSAdgDSLPkMaVAwljYxGat/TSONMZ1eoafezKonRohE7QE3TdjD/8V+3AS3fZ0LtroqUIlnp8pp8RNRNfBA01ZYMJ4UJpOIcLLVrPjjUOCBqrif1eNEJzyz4SAlaNvoMLE15pmEmoxP3C94HFxB8agglVRT4Tj9vF4VthFi3qRVbNrLlWeQE6BAvmW1X9tZRE29KwDbMs/wjixK8k0wJZOVtLlB3TGqdAv560WtWAofgPcDfuDY/25IDXaZU0aeu51hSx1khnOHFnd3uvx8usjT91jhKIbmbbVVFQwX0tneu57h3kwUncaxsISWYxXZ2nQdcsjDfaWvIqXyXzVIYEeS4XQuns1dPaQWS0mKSmNcdvEWu70oMUzrb6o+THtkUD7x4JKL3iANqq6mhRed1Uj9+zxYDyvHmeWutaQ1NnC+CwmJpxVCMxopO/ECMI9GMDI28RpW4=
    file: "target/spt-development-cid-${POM_VERSION}.jar"
    skip_cleanup: true
    on:
      branch: main